name: Code Quality

on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  quality:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install CodeCutter
        run: powershell Invoke-WebRequest -Uri "https://github.com/dragonfruitnetwork/CodeCutter/releases/latest/download/DragonFruit.CodeCutter.exe" -OutFile ".\DragonFruit.CodeCutter.exe"

      - name: "Setup MSBuild"
        uses: microsoft/setup-msbuild@v1.0.2

      - name: NuGet Restore
        run: |
          nuget locales all -clear
          nuget restore

      - name: Code Quality Check
        run: ".\\DragonFruit.CodeCutter.exe"
