name: Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PowerShell Policy
        run: Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force

      - name: NuGet Build and Publish (Release)
        run: ./res/Nuget.ps1 -ApiKey ${{ secrets.NUGET_KEY }}
        if: "!github.event.release.prerelease"

      - name: Nuget Build and Publish (Beta)
        run: ./res/Nuget.ps1 -ApiKey ${{ secrets.NUGET_KEY }} -Suffix "-beta"
        if: "github.event.release.prerelease"
